# Sozialrecht RAG - Neo4j Setup
# Docker Compose für lokale Entwicklung

version: '3.8'

services:
  neo4j:
    image: neo4j:5.25.0-community
    container_name: sozialrecht-neo4j
    ports:
      - "7474:7474"  # HTTP Browser
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2g
      - NEO4J_dbms_memory_pagecache_size=512m
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - sozialrecht-network
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p password 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  neo4j_data:
    name: sozialrecht_neo4j_data
  neo4j_logs:
    name: sozialrecht_neo4j_logs
  neo4j_import:
    name: sozialrecht_neo4j_import
  neo4j_plugins:
    name: sozialrecht_neo4j_plugins

networks:
  sozialrecht-network:
    name: sozialrecht-network
    driver: bridge
